-- init_local.sql
-- Base local de Alice/Bob: QKD_keys_KMS1

DROP USER IF EXISTS ''@'localhost';
DROP USER IF EXISTS ''@'%';

CREATE DATABASE IF NOT EXISTS QKD_keys_KMS1
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE QKD_keys_KMS1;

CREATE TABLE IF NOT EXISTS QKD_keys (
    key_id VARCHAR(40) PRIMARY KEY,
    key_value VARCHAR(1290) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'QKD'@'localhost' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'QKD'@'127.0.0.1' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'QKD'@'%' IDENTIFIED BY '';

CREATE USER IF NOT EXISTS 'KMS'@'localhost' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'KMS'@'127.0.0.1' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'KMS'@'%' IDENTIFIED BY '';

GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'QKD'@'localhost';
GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'QKD'@'127.0.0.1';
GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'QKD'@'%';

GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'KMS'@'localhost';
GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'KMS'@'127.0.0.1';
GRANT ALL PRIVILEGES ON QKD_keys_KMS1.* TO 'KMS'@'%';

FLUSH PRIVILEGES;